const ROLES = {
  ADMINISTRADOR: "ADMINISTRADOR",
  BOSS: "BOSS",
  SUPERVISOR: "SUPERVISOR",
  EMPLOYEE: "EMPLOYEE",
};

const DOWNLOAD_ALLOWED_ROLES = [
  ROLES.ADMINISTRADOR,
  ROLES.BOSS,
  ROLES.SUPERVISOR,
];

module.exports = {
  ROLES,
  DOWNLOAD_ALLOWED_ROLES,
};
